### ISSUE TITLE
Multiline support?

### ISSUE THREAD

**Issue by chenglou** [erikbrinkman/language-tup#1]
@erikbrinkman the sublime-text version's tmLanguage file (https://github.com/petervaro/tup/blob/ec80db8fb551242e6d0ee2bb29918d4ade5b5330/langs/tup.tmLanguage) supports it. It would be great if this did too!

Thanks.

**Comment by erikbrinkman** [comment]
What do you mean by multiline support? As far as I'm aware, tup syntax does not support multiline commands, so by definition the grammar shouldn't need to support it. Can you show me an example of what you're looking for?

**Comment by chenglou** [comment]
It does actually, and that's mostly what I use =]

```
: someDep1 someDep2 someDep3 \
  |> commandHere \
  |> outputHere
```

Makes the input & output lines much more readable!

**Comment by erikbrinkman** [comment]
I was unaware that tup allowed escaping newlines, I'll look into adding this to the grammar.

**Comment by chenglou** [comment]
Thanks!
